name: AncientCraft
version: '${project.version}'
main: me.enderlight3336.ancientcraft.AncientCraft
api-version: '1.20'
load: STARTUP
commands:
  ancientcraft:
    usage: ""
    description: ""
  ac:
    usage: ""